/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Jessica
 */
public class CreatePanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatePanel
     */
    public CreatePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderGroup = new javax.swing.ButtonGroup();
        female = new javax.swing.JRadioButton();
        male = new javax.swing.JRadioButton();
        color = new javax.swing.JComboBox<>();
        shading = new javax.swing.JComboBox<>();
        tabby = new javax.swing.JComboBox<>();
        point = new javax.swing.JComboBox<>();
        silver = new javax.swing.JCheckBox();
        charcoal = new javax.swing.JCheckBox();
        white = new javax.swing.JCheckBox();
        torti = new javax.swing.JCheckBox();
        catID = new javax.swing.JTextField();
        ownerID = new javax.swing.JTextField();
        catLabel = new javax.swing.JLabel();
        ownerLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        buildLabel = new javax.swing.JLabel();
        colorLabel = new javax.swing.JLabel();
        shadingLabel = new javax.swing.JLabel();
        tabbyLabel = new javax.swing.JLabel();
        pointLabel = new javax.swing.JLabel();
        build = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        createButton1 = new javax.swing.JButton();
        genderCheck = new javax.swing.JCheckBox();
        careLabel = new javax.swing.JLabel();
        buildCheck = new javax.swing.JCheckBox();
        colorCheck = new javax.swing.JCheckBox();
        shadingCheck = new javax.swing.JCheckBox();
        tabbyCheck = new javax.swing.JCheckBox();
        pointsCheck = new javax.swing.JCheckBox();

        genderGroup.add(female);
        female.setText("Female");

        genderGroup.add(male);
        male.setText("Male");

        color.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorActionPerformed(evt);
            }
        });

        shading.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        shading.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shadingActionPerformed(evt);
            }
        });

        tabby.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        tabby.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabbyActionPerformed(evt);
            }
        });

        point.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        point.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pointActionPerformed(evt);
            }
        });

        silver.setText("silver");
        silver.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                silverItemStateChanged(evt);
            }
        });

        charcoal.setText("charcoal");
        charcoal.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                charcoalItemStateChanged(evt);
            }
        });

        white.setText("white");
        white.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                whiteItemStateChanged(evt);
            }
        });

        torti.setText("tortoiseshell");
        torti.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tortiItemStateChanged(evt);
            }
        });

        catID.setText("ID here");

        ownerID.setText("ID here");

        catLabel.setText("Cat ID: ");

        ownerLabel.setText("Owner ID: ");

        genderLabel.setText("Gender: ");

        buildLabel.setText("Build: ");

        colorLabel.setText("Color: ");

        shadingLabel.setText("Shading: ");

        tabbyLabel.setText("Tabby: ");

        pointLabel.setText("Points: ");

        build.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        build.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buildActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setToolTipText("");

        createButton1.setText("Create!");

        genderCheck.setText("Gender");
        genderCheck.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                genderCheckItemStateChanged(evt);
            }
        });

        careLabel.setText("Don't care about...");

        buildCheck.setText("Build");
        buildCheck.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                buildCheckItemStateChanged(evt);
            }
        });

        colorCheck.setText("Color");
        colorCheck.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                colorCheckItemStateChanged(evt);
            }
        });

        shadingCheck.setText("Shading");
        shadingCheck.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                shadingCheckItemStateChanged(evt);
            }
        });

        tabbyCheck.setText("Tabby");
        tabbyCheck.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tabbyCheckItemStateChanged(evt);
            }
        });

        pointsCheck.setText("Points");
        pointsCheck.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                pointsCheckItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ownerLabel)
                            .addComponent(catLabel)
                            .addComponent(genderLabel)
                            .addComponent(buildLabel)
                            .addComponent(colorLabel)
                            .addComponent(shadingLabel)
                            .addComponent(tabbyLabel)
                            .addComponent(pointLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(shading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(point, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tabby, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(silver)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(charcoal))
                            .addComponent(male)
                            .addComponent(catID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ownerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(female)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(torti)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(white))
                            .addComponent(build, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(createButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(genderCheck)
                    .addComponent(careLabel)
                    .addComponent(buildCheck)
                    .addComponent(colorCheck)
                    .addComponent(shadingCheck)
                    .addComponent(tabbyCheck)
                    .addComponent(pointsCheck))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(catLabel)
                            .addComponent(catID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ownerLabel)
                            .addComponent(ownerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(genderLabel)
                            .addComponent(female))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(male)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buildLabel)
                            .addComponent(build, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(colorLabel)
                            .addComponent(torti)
                            .addComponent(white))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(shading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shadingLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tabby, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tabbyLabel)
                            .addComponent(silver)
                            .addComponent(charcoal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(point, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pointLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(createButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(careLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(genderCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buildCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(colorCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(shadingCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tabbyCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pointsCheck)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colorActionPerformed

    private void shadingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shadingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shadingActionPerformed

    private void tabbyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabbyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tabbyActionPerformed

    private void pointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pointActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pointActionPerformed

    private void silverItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_silverItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_silverItemStateChanged

    private void charcoalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_charcoalItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_charcoalItemStateChanged

    private void whiteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_whiteItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_whiteItemStateChanged

    private void tortiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tortiItemStateChanged

        if (evt.getStateChange() == java.awt.event.ItemEvent.DESELECTED) {
            // TODO add your handling code here:
        }

    }//GEN-LAST:event_tortiItemStateChanged

    private void buildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buildActionPerformed

    private void genderCheckItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_genderCheckItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_genderCheckItemStateChanged

    private void buildCheckItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_buildCheckItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_buildCheckItemStateChanged

    private void colorCheckItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_colorCheckItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_colorCheckItemStateChanged

    private void shadingCheckItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_shadingCheckItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_shadingCheckItemStateChanged

    private void tabbyCheckItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tabbyCheckItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tabbyCheckItemStateChanged

    private void pointsCheckItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_pointsCheckItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_pointsCheckItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> build;
    private javax.swing.JCheckBox buildCheck;
    private javax.swing.JLabel buildLabel;
    private javax.swing.JLabel careLabel;
    private javax.swing.JTextField catID;
    private javax.swing.JLabel catLabel;
    private javax.swing.JCheckBox charcoal;
    private javax.swing.JComboBox<String> color;
    private javax.swing.JCheckBox colorCheck;
    private javax.swing.JLabel colorLabel;
    private javax.swing.JButton createButton1;
    private javax.swing.JRadioButton female;
    private javax.swing.JCheckBox genderCheck;
    private javax.swing.ButtonGroup genderGroup;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField ownerID;
    private javax.swing.JLabel ownerLabel;
    private javax.swing.JComboBox<String> point;
    private javax.swing.JLabel pointLabel;
    private javax.swing.JCheckBox pointsCheck;
    private javax.swing.JComboBox<String> shading;
    private javax.swing.JCheckBox shadingCheck;
    private javax.swing.JLabel shadingLabel;
    private javax.swing.JCheckBox silver;
    private javax.swing.JComboBox<String> tabby;
    private javax.swing.JCheckBox tabbyCheck;
    private javax.swing.JLabel tabbyLabel;
    private javax.swing.JCheckBox torti;
    private javax.swing.JCheckBox white;
    // End of variables declaration//GEN-END:variables
}
