/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Jessica
 */
public class ImportPanel extends javax.swing.JPanel {

    /**
     * Creates new form ImportPanel
     */
    public ImportPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        iDLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        buildCheck = new javax.swing.JCheckBox();
        colorLabel = new javax.swing.JLabel();
        tortiLabel = new javax.swing.JLabel();
        shadingLabel = new javax.swing.JLabel();
        tabbyLabel = new javax.swing.JLabel();
        silverCheck = new javax.swing.JCheckBox();
        charcoalCheck = new javax.swing.JCheckBox();
        pointsLabel = new javax.swing.JLabel();
        whiteLabel = new javax.swing.JLabel();
        iDBox = new javax.swing.JTextField();
        genderBox = new javax.swing.JCheckBox();
        buildBox = new javax.swing.JComboBox<>();
        colorBox = new javax.swing.JComboBox<>();
        tortiBox = new javax.swing.JCheckBox();
        shadingBox = new javax.swing.JComboBox<>();
        tabbyBox = new javax.swing.JComboBox<>();
        SilverBox = new javax.swing.JCheckBox();
        CharcoalBox = new javax.swing.JCheckBox();
        PointsBox = new javax.swing.JComboBox<>();
        WhiteBox = new javax.swing.JCheckBox();
        BuildLoci = new javax.swing.JCheckBox();
        Build1 = new javax.swing.JComboBox<>();
        Build2 = new javax.swing.JComboBox<>();
        Build3 = new javax.swing.JComboBox<>();
        Build4 = new javax.swing.JComboBox<>();
        Build5 = new javax.swing.JComboBox<>();
        Build6 = new javax.swing.JComboBox<>();
        Build7 = new javax.swing.JComboBox<>();
        Build8 = new javax.swing.JComboBox<>();
        ColorLoci = new javax.swing.JCheckBox();
        Color1 = new javax.swing.JComboBox<>();
        Color2 = new javax.swing.JComboBox<>();
        Tanning1 = new javax.swing.JComboBox<>();
        Tanning2 = new javax.swing.JComboBox<>();
        Dilute1 = new javax.swing.JComboBox<>();
        Dilute2 = new javax.swing.JComboBox<>();
        Bleaching1 = new javax.swing.JComboBox<>();
        Bleaching2 = new javax.swing.JComboBox<>();
        Amber1 = new javax.swing.JComboBox<>();
        Amber2 = new javax.swing.JComboBox<>();
        TabbyLoci = new javax.swing.JCheckBox();
        Tabby1 = new javax.swing.JComboBox<>();
        Tabby2 = new javax.swing.JComboBox<>();
        Tick1 = new javax.swing.JComboBox<>();
        Tick2 = new javax.swing.JComboBox<>();
        Spot1 = new javax.swing.JComboBox<>();
        Spot2 = new javax.swing.JComboBox<>();
        Mack1 = new javax.swing.JComboBox<>();
        Mack2 = new javax.swing.JComboBox<>();
        Rose1 = new javax.swing.JComboBox<>();
        Rose2 = new javax.swing.JComboBox<>();
        ShadingLoci = new javax.swing.JCheckBox();
        Shading1 = new javax.swing.JComboBox<>();
        Shading2 = new javax.swing.JComboBox<>();
        Golden1 = new javax.swing.JComboBox<>();
        Golden2 = new javax.swing.JComboBox<>();
        PointLoci = new javax.swing.JCheckBox();
        Point1 = new javax.swing.JComboBox<>();
        Point2 = new javax.swing.JComboBox<>();
        WhiteLoci = new javax.swing.JCheckBox();
        White1 = new javax.swing.JComboBox<>();
        White2 = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        bunnyBox = new javax.swing.JCheckBox();
        lionBox = new javax.swing.JCheckBox();
        chimBox = new javax.swing.JCheckBox();
        importButton = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(560, 370));
        setPreferredSize(new java.awt.Dimension(900, 550));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("7 - Kristoff - toffeeca - Common - XY bbbbl dddd vv Pa(ll)Pb(Ll) CC aa TiTi HsHs GG RR ss - Male Shaded Lilac with Minimal White\n436 XY CoWi CoOr SuWi CoOr OO blbl dd Dmdm ee Aa tt spsp Mcmc Roro iI gG CC SS - Male Wild Cream Golden Shaded with White");
        jScrollPane1.setViewportView(jTextArea1);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        iDLabel.setText("Cat ID: ");

        genderLabel.setText("Gender: ");

        buildCheck.setText("Build: ");

        colorLabel.setText("Color: ");

        tortiLabel.setText("Tortoiseshell: ");

        shadingLabel.setText("Shading: ");

        tabbyLabel.setText("Tabby: ");

        silverCheck.setText("Silver: ");

        charcoalCheck.setText("Charcoal: ");

        pointsLabel.setText("Points: ");

        whiteLabel.setText("White: ");

        iDBox.setMinimumSize(new java.awt.Dimension(36, 26));
        iDBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iDBoxActionPerformed(evt);
            }
        });

        genderBox.setText("Female");

        buildBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wild", "Cobby", "Oriental", "Substantial" }));

        colorBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Black", "Chocolate", "Cinnamon", "Amber", "Orange", "Blue", "Lilac", "Fawn", "Light Amber", "Cream", "Caramel", "Apricot" }));

        tortiBox.setText("Yes");

        shadingBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NA", "Silver Shaded", "Golden Shaded", "Silver Chin", "Golden Chin" }));

        tabbyBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Self", "Ticked", "Spotted", "Mackerel", "Classic", "Residual", "Rosetted", "Braided", "Marbled", "Broken", "Sokoke" }));

        SilverBox.setText("Yes");

        CharcoalBox.setText("Yes");

        PointsBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NA", "Siamese", "Mink", "Burmese" }));

        WhiteBox.setText("Yes");

        BuildLoci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuildLociActionPerformed(evt);
            }
        });

        Build1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wi", "Co", "Or", "Su" }));
        Build1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Build1ActionPerformed(evt);
            }
        });

        Build2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wi", "Co", "Or", "Su" }));

        Build3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wi", "Co", "Or", "Su" }));

        Build4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wi", "Co", "Or", "Su" }));

        Build5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wi", "Co", "Or", "Su" }));

        Build6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wi", "Co", "Or", "Su" }));

        Build7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wi", "Co", "Or", "Su" }));

        Build8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wi", "Co", "Or", "Su" }));

        Color1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "O", "o" }));

        Color2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "O", "o" }));

        Tanning1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "B", "b", "bl" }));

        Tanning2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "B", "b", "bl" }));

        Dilute1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "D", "d" }));

        Dilute2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "D", "d" }));

        Bleaching1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dm", "dm" }));

        Bleaching2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dm", "dm" }));

        Amber1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "E", "e" }));

        Amber2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "E", "e" }));

        TabbyLoci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TabbyLociActionPerformed(evt);
            }
        });

        Tabby1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "Ap", "a" }));

        Tabby2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "Ap", "a" }));

        Tick1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ta", "t" }));

        Tick2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ta", "t" }));

        Spot1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sp", "sp" }));

        Spot2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sp", "sp" }));

        Mack1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mc", "mc" }));

        Mack2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mc", "mc" }));

        Rose1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ro", "ro" }));

        Rose2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ro", "ro" }));

        Shading1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "I", "i" }));

        Shading2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "I", "i" }));

        Golden1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "G", "g" }));

        Golden2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "G", "g" }));

        Point1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C", "cs", "cb" }));

        Point2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C", "cs", "cb" }));

        White1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S", "s" }));

        White2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S", "s" }));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        bunnyBox.setText("Bunny");

        lionBox.setText("Lion");

        chimBox.setText("Chimaeric Tortoiseshell");

        importButton.setText("Import");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(iDLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(genderLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(buildCheck))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(colorLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(tortiLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(shadingLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(tabbyLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(silverCheck))
                    .addComponent(charcoalCheck)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(pointsLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(whiteLabel)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iDBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genderBox)
                    .addComponent(buildBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colorBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tortiBox)
                    .addComponent(shadingBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tabbyBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SilverBox)
                    .addComponent(CharcoalBox)
                    .addComponent(PointsBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WhiteBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BuildLoci)
                    .addComponent(Build1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Build2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Build3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Build4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Build5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Build6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Build7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Build8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ColorLoci)
                    .addComponent(Color1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Color2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tanning1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tanning2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dilute1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dilute2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bleaching1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bleaching2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Amber1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Amber2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TabbyLoci)
                    .addComponent(Tabby1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tabby2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tick1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tick2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Spot1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Spot2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mack1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mack2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Rose1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Rose2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Golden1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Golden2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ShadingLoci)
                            .addComponent(Shading1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Shading2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PointLoci)
                    .addComponent(Point1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Point2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WhiteLoci)
                    .addComponent(White1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(White2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bunnyBox)
                            .addComponent(lionBox)
                            .addComponent(chimBox))
                        .addContainerGap(62, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(importButton)
                        .addContainerGap())))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BuildLoci)
                                .addGap(5, 5, 5)
                                .addComponent(Build1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(Build2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(Build3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(Build4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(Build5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(Build6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(Build7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(Build8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ColorLoci)
                                .addGap(5, 5, 5)
                                .addComponent(Color1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(Color2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(Tanning1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(Tanning2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(Dilute1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(Dilute2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(Bleaching1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(Bleaching2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(Amber1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(Amber2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TabbyLoci)
                                .addGap(5, 5, 5)
                                .addComponent(Tabby1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(Tabby2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(Tick1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(Tick2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(Spot1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(Spot2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(Mack1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(Mack2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(Rose1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(Rose2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ShadingLoci)
                                .addGap(5, 5, 5)
                                .addComponent(Shading1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(Shading2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(Golden1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(Golden2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PointLoci)
                                .addGap(5, 5, 5)
                                .addComponent(Point1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(Point2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(WhiteLoci)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(White1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(White2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(iDLabel)
                                .addGap(12, 12, 12)
                                .addComponent(genderLabel)
                                .addGap(9, 9, 9)
                                .addComponent(buildCheck)
                                .addGap(10, 10, 10)
                                .addComponent(colorLabel)
                                .addGap(12, 12, 12)
                                .addComponent(tortiLabel)
                                .addGap(13, 13, 13)
                                .addComponent(shadingLabel)
                                .addGap(15, 15, 15)
                                .addComponent(tabbyLabel)
                                .addGap(8, 8, 8)
                                .addComponent(silverCheck)
                                .addGap(1, 1, 1)
                                .addComponent(charcoalCheck)
                                .addGap(8, 8, 8)
                                .addComponent(pointsLabel)
                                .addGap(12, 12, 12)
                                .addComponent(whiteLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(iDBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(genderBox)
                                .addGap(5, 5, 5)
                                .addComponent(buildBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(colorBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(tortiBox)
                                .addGap(5, 5, 5)
                                .addComponent(shadingBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(tabbyBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(SilverBox)
                                .addGap(1, 1, 1)
                                .addComponent(CharcoalBox)
                                .addGap(5, 5, 5)
                                .addComponent(PointsBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(WhiteBox))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bunnyBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lionBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chimBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(importButton))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void iDBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iDBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iDBoxActionPerformed

    private void BuildLociActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuildLociActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuildLociActionPerformed

    private void TabbyLociActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TabbyLociActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TabbyLociActionPerformed

    private void Build1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Build1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Build1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Amber1;
    private javax.swing.JComboBox<String> Amber2;
    private javax.swing.JComboBox<String> Bleaching1;
    private javax.swing.JComboBox<String> Bleaching2;
    private javax.swing.JComboBox<String> Build1;
    private javax.swing.JComboBox<String> Build2;
    private javax.swing.JComboBox<String> Build3;
    private javax.swing.JComboBox<String> Build4;
    private javax.swing.JComboBox<String> Build5;
    private javax.swing.JComboBox<String> Build6;
    private javax.swing.JComboBox<String> Build7;
    private javax.swing.JComboBox<String> Build8;
    private javax.swing.JCheckBox BuildLoci;
    private javax.swing.JCheckBox CharcoalBox;
    private javax.swing.JComboBox<String> Color1;
    private javax.swing.JComboBox<String> Color2;
    private javax.swing.JCheckBox ColorLoci;
    private javax.swing.JComboBox<String> Dilute1;
    private javax.swing.JComboBox<String> Dilute2;
    private javax.swing.JComboBox<String> Golden1;
    private javax.swing.JComboBox<String> Golden2;
    private javax.swing.JComboBox<String> Mack1;
    private javax.swing.JComboBox<String> Mack2;
    private javax.swing.JComboBox<String> Point1;
    private javax.swing.JComboBox<String> Point2;
    private javax.swing.JCheckBox PointLoci;
    private javax.swing.JComboBox<String> PointsBox;
    private javax.swing.JComboBox<String> Rose1;
    private javax.swing.JComboBox<String> Rose2;
    private javax.swing.JComboBox<String> Shading1;
    private javax.swing.JComboBox<String> Shading2;
    private javax.swing.JCheckBox ShadingLoci;
    private javax.swing.JCheckBox SilverBox;
    private javax.swing.JComboBox<String> Spot1;
    private javax.swing.JComboBox<String> Spot2;
    private javax.swing.JComboBox<String> Tabby1;
    private javax.swing.JComboBox<String> Tabby2;
    private javax.swing.JCheckBox TabbyLoci;
    private javax.swing.JComboBox<String> Tanning1;
    private javax.swing.JComboBox<String> Tanning2;
    private javax.swing.JComboBox<String> Tick1;
    private javax.swing.JComboBox<String> Tick2;
    private javax.swing.JComboBox<String> White1;
    private javax.swing.JComboBox<String> White2;
    private javax.swing.JCheckBox WhiteBox;
    private javax.swing.JCheckBox WhiteLoci;
    private javax.swing.JComboBox<String> buildBox;
    private javax.swing.JCheckBox buildCheck;
    private javax.swing.JCheckBox bunnyBox;
    private javax.swing.JCheckBox charcoalCheck;
    private javax.swing.JCheckBox chimBox;
    private javax.swing.JComboBox<String> colorBox;
    private javax.swing.JLabel colorLabel;
    private javax.swing.JCheckBox genderBox;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JTextField iDBox;
    private javax.swing.JLabel iDLabel;
    private javax.swing.JButton importButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JCheckBox lionBox;
    private javax.swing.JLabel pointsLabel;
    private javax.swing.JComboBox<String> shadingBox;
    private javax.swing.JLabel shadingLabel;
    private javax.swing.JCheckBox silverCheck;
    private javax.swing.JComboBox<String> tabbyBox;
    private javax.swing.JLabel tabbyLabel;
    private javax.swing.JCheckBox tortiBox;
    private javax.swing.JLabel tortiLabel;
    private javax.swing.JLabel whiteLabel;
    // End of variables declaration//GEN-END:variables
}
